import { KaTableLang } from "./ka_table";

export const langCN = {
    toolbarRefresh: '刷新',
    toolbarFilter: '筛选',
    toolbarSort: '排序',
    toolbarEdit: '编辑',
    toolbarRemove: '删除',
    toolbarAdd: '新增',
    toolbarExport: '导出',
    toolbarImport: '导入',
    noChange: '没啥需要更新',
    refreshError: '刷新失败',
    exportError: '导出失败',
    addError: '新增失败',
    editError: '更新失败',
    removeError: '删除失败',
    importError: '导入失败',
    addSuccess: '新增成功',
    editSuccess: '修改成功',
    removeConfirm: '确认删除',
    removeSuccess: '删除成功',
    importSuccess: '导入成功',
    loadError: '读取数据失败',
    importNoFileError: '没有文件',
    importFileError: '导入文件失败',
    templateError: '下载模板失败',
    selectRow: '请先选中一行',
    confirm: '确定',
    clear: '清空',
    submit: '提交',
    reset: '重置',
    cancel: '取消',
    summaryTotal: '共',
    all:'全部',
    curPage:'本页',
    and:'且',
    or:'或',
    equal:'=',
	notEqual:'不等于',
	greaterThan:'>',
	greaterThanOrEqual:'>=',
	lessThan:'<',
	lessThanOrEqual:'<=',
	beginWith:'开头于',
	endWith:'结尾于',
	contain:'包含',
	empty:'空',
	notEmpty:'不为空',
} as KaTableLang

export const langEN = {
    toolbarRefresh: 'refresh',
    toolbarFilter: 'filter',
    toolbarSort: 'sort',
    toolbarEdit: 'edit',
    toolbarRemove: 'remove',
    toolbarAdd: 'add',
    toolbarExport: 'export',
    toolbarImport: 'import',
    noChange: 'no change',
    refreshError: 'refresh fail',
    exportError: 'export fail',
    addError: 'add fail',
    editError: 'update fail',
    removeConfirm:'confirm remove',
    removeError: 'remove fail',
    importError: 'import fail',
    addSuccess: 'add success',
    editSuccess: 'update success',
    removeSuccess: 'remove success',
    importSuccess: 'import success',
    loadError: 'load data fail',
    importNoFileError: 'no file',
    importFileError: 'import file fail',
    templateError: 'download template fail',
    selectRow: 'please select a row first',
    confirm: 'confirm',
    clear: 'clear',
    submit: 'submit',
    reset: 'reset',
    cancel: 'cancel',
    summaryTotal: 'total',
    all:'all',
    curPage:'current page',
    and:'and',
    or:'or',
    equal:'=',
	notEqual:'not equal',
	greaterThan:'>',
	greaterThanOrEqual:'>=',
	lessThan:'<',
	lessThanOrEqual:'<=',
	beginWith:'begin with',
	endWith:'end with',
	contain:'contain',
	empty:'empty',
	notEmpty:'not empty',
} as KaTableLang